### ISSUE TITLE
Automatically determined values for timezone and currency

### ISSUE THREAD

**Issue by McSodbrenner** [salarmehr/cosmopolitan#2]
In your example you have the timezone and the currency identifier as external values, but it is possible to determine them:

```
$locale = 'de-DE';

$country_code = Locale::getRegion($locale);
$timezone = DateTimeZone::listIdentifiers(\DateTimeZone::PER_COUNTRY, $country_code)[0];
$currency = (new NumberFormatter($locale, NumberFormatter::CURRENCY))->getTextAttribute(NumberFormatter::CURRENCY_CODE);

print_r([$country_code, $timezone, $currency]);
```

To be fair: :) The timezone is a one-to-many-relationsship, but should work for most countries.
And if we have this values we would be able to omit these parameters in those methods:
```
language()
country()
currency()
money()
```

So you would have just to type $intl->language() to get the current language.
What do you think?

**Comment by salarmehr** [comment]
@McSodbrenner thanks for your suggestions. 

Please check out the new implementation. Now `Intl` class will detect a default currency if the region is provided in the locale identifier (or you can send a currency to the constructor). This way in the single-locale applications you don't need to repeat the currency code for each monetary value. 

Regarding the time zone, you provided example does not work for countries with more than a single time zone and, for example, using en_AU it returns an uncommon TZ for Australia. And I believe that it's Important to explicitly specify the time zone in the constructor. 

User may be in any possible time zone regardless of the region subtag (if it is presented in the first place). 

Also please be advised that once you created an instance of the `Intl` class, it's expected that you store it in a service container and reuse it throughout the application so you need to specify the timezone once ( if it is not the default time zone of PHP env).

I also thought to make the parameter of the language and country optional. To return the current language and country of current Locale. Currently, for all localiser methods, we need to send a value and get a localised string. Currently, to get the current langue and country (if presented) we need to you use the following example:
```php
$intl= new Locale('de_DE');
echo $intl->country($intl->locale);
echo $intl->language($intl->locale);
```
Maybe distinct methods can lead to a more reliable implementation because of the lack of 
method overwriting polymorphism in PHP. What do you think?

**Comment by McSodbrenner** [comment]
**Currency**
Thanks a lot. Would also be nice if currency() would not need a parameter either.

**Timezone**
Yes you are right. Let's skip this idea. :)

Do you have a practical example for the last point? I am not sure why additional methods are needed here.

**Comment by salarmehr** [comment]
@McSodbrenner Ok, I made the parameters of the following methods optional

language()
country()
currency()
direction()
flag()

Yes, the flag method is a new cool one that returns the emoji flag of the country. 

Feel free to create PR too.

**Comment by McSodbrenner** [comment]
Great update. I could completely remove my wrapper class that does exactly these things! :)

**Comment by salarmehr** [comment]
@McSodbrenner  v3 has just been released. You can now use the same interface across multiple languages. Please give it a try, and let me know your thoughts. https://cosmo.miloun.com/?lang=php
